### ISSUE TITLE
counld not find 'library(fun) packets"

### ISSUE THREAD

**Issue by BeautifulDJ** [krzysztof99xd/SNA4DSProject#14]
hello sir, could not find the packets library(snafun), why...

**Comment by iamvishalsehgal** [comment]
Install Snafun and Dependencies by [Claudia and Roger](https://github.com/SNAnalyst/SNAfun/):
   - Open RStudio.
   - Install the `remotes` package by running:
     ```R
     install.packages("remotes")
     ```
   - Install the `rstudio.prefs` package:
     ```R
     remotes::install.packages("rstudio.prefs")
     ```
   - Install the `snaverse` package:
     ```R
     remotes::install_github("SNAnalyst/snaverse", dependencies = TRUE, force = TRUE)
     ```
   - Set up the RStudio IDE for SNA4DS:
     ```R
     snaverse::rstudiofy(setup = "SNA4DS")
     ```
   - Install all packages needed for `snaverse`:
     ```R
     snaverse::packagefy(install = "all")
     ```
   - Finally, install the Snafun suite:
     ```R
     snaverse::snaversify(install = "snaverse")
     ```

**Comment by BeautifulDJ** [comment]
excuse me, but...just directly download the following packets?
![QQ截图20240604212447](https://github.com/krzysztof99xd/SNA4DSProject/assets/145675638/1008ede5-138a-4e99-bd81-e40ac22239b8)
